namespace TelemetryApp.Api.Model;

/// <summary>
/// Configuration options for OpenTelemetry logging, tracing and metrics.
/// </summary>
public sealed class TelemetryOptions
{
    /// <summary>
    /// Configuration section name within <c>appsettings.json</c>.
    /// </summary>
    public const string SectionName = "Telemetry";

    /// <summary>
    /// Gets or sets a value indicating whether telemetry is enabled.
    /// If disabled, no OpenTelemetry services are registered.
    /// </summary>
    public bool Enabled { get; set; } = true;

    /// <summary>
    /// Gets or sets the OTLP endpoint used to export logs, traces and metrics.
    /// Example: <c>http://localhost:4318</c>.
    /// </summary>
    public string Endpoint { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets optional OTLP exporter headers.
    /// Can be used for authentication or routing information.
    /// </summary>
    public string Headers { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the logical service name reported to the telemetry backend.
    /// </summary>
    public string ServiceName { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the environment name reported to the telemetry backend.
    /// </summary>
    public string EnvironmentName { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets a value indicating whether distributed tracing is enabled.
    /// </summary>
    public bool EnableTracing { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether metrics collection is enabled.
    /// </summary>
    public bool EnableMetrics { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether log export is enabled.
    /// </summary>
    public bool EnableLogging { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether ASP.NET Core request instrumentation is enabled.
    /// </summary>
    public bool EnableAspNetCoreInstrumentation { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether outgoing HTTP client requests are instrumented.
    /// </summary>
    public bool EnableHttpClientInstrumentation { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether SQL client database calls are instrumented.
    /// </summary>
    public bool EnableSqlClientInstrumentation { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether .NET runtime metrics
    /// such as garbage collection, memory usage and thread statistics are collected.
    /// </summary>
    public bool EnableRuntimeInstrumentation { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether exceptions are recorded
    /// on spans generated by instrumentations that support exception tracking.
    /// </summary>
    public bool RecordExceptions { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether health check endpoints
    /// should be excluded from telemetry collection.
    /// Recommended for production environments to reduce telemetry noise.
    /// </summary>
    public bool ExcludeHealthChecks { get; set; } = true;
}